language: java
sudo: false
dist: trusty

jdk: oraclejdk8

script: ./mvnw -Prun-its clean install

branches:
    except:
        - gh-pages

notifications:
  email:
    - matthieu@brouillard.fr
