language: java
sudo: false
dist: trusty

jdk: oraclejdk8

script: mvn -Prun-its clean install 

branches:
    except:
        - gh-pages

notifications:
  email:
    - matthieu@brouillard.fr
