language: bash

sudo: required

services:
  - docker

before_script:
  - chmod a+x src/ci/build-with-external-it-fallback.sh

script:
  - docker run --rm -v $(pwd):/root/sources -w /root/sources maven:3.3.9-jdk-8 ./src/ci/build-with-external-it-fallback.sh

after_failure:
  - find target/it -name *.log -exec echo {} \; -exec cat {} \;

branches:
    except:
        - gh-pages

notifications:
  email:
    - matthieu@brouillard.fr
